### ISSUE TITLE
Translator is awesome but its getting offline.

### ISSUE THREAD

**Issue by khawajamechatronics** [luisgbr1el/TranslatorBOT#1]
Hi,

I am not sure if this is right place to report offline status of translator. Is there some issue? can someone guide me?

**Comment by luisgbr1el** [comment]
No, the right place to report this is on support server on Discord. And it isn't an issue.

Server link: https://discord.gg/stSDv9T

**Comment by luisgbr1el** [comment]
> Hi,
> 
> I am not sure if this is right place to report offline status of translator. Is there some issue? can someone guide me?

I think the right place to report this is on our support server on Discord.
This is not a issue, we were just with some problems with the Bot Hosting.

Server link: https://discord.gg/stSDv9T
