### ISSUE TITLE
Double Massenges 

### ISSUE THREAD

**Issue by EvilPsych0** [luisgbr1el/TranslatorBOT#4]
Hey, i Just installed the bot on my discord server and try out the functions soon i notice i get double messages each time. tried it on a different server too same result.
![double massenges](https://user-images.githubusercontent.com/86798345/124173689-aa846c00-daab-11eb-8f68-e381dc6058f0.jpg)

Bot version 1.4.0 | 2021
Got the bot from here: https://top.gg/bot/745021822361141278

**Comment by luisgbr1el** [comment]
Fixed! Thank you for reporting.

**Comment by luisgbr1el** [comment]
> Hey, i Just installed the bot on my discord server and try out the functions soon i notice i get double messages each time. tried it on a different server too same result.
> ![double massenges](https://user-images.githubusercontent.com/86798345/124173689-aa846c00-daab-11eb-8f68-e381dc6058f0.jpg)
> 
> Bot version 1.4.0 | 2021
> Got the bot from here: https://top.gg/bot/745021822361141278

Fixed! Thank you for reporting.
